## YAML Template.
spring.datasource.url: jdbc:mysql://localhost:3306/mysql
spring.datasource.username: root
spring.datasource.password: Ujapack1
spring.jpa.properties.javax.persistence.schema-generation.database.action: drop-and-create
spring.data.jpa.repositories.bootstrap-mode: default
